version: "2.2"
services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ibugsec
      MONGO_INITDB_ROOT_PASSWORD: k2l9g3v1
    ports:
      - "27017:27017"
  web:
    image: httpd:latest
    container_name: web
    env_file:
      - httpd.env
    environment:
      - APACHE_DOC_ROOT=/public_html/atos
    ports:
      - "80:80"


networks:
  mongo-compose-network:
    driver: bridge