version: "2.2"
services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ibugsec
      MONGO_INITDB_ROOT_PASSWORD: k2l9g3v1
    ports:
      - "27017:27017"
  apache:
    image: 'php:7.2-apache'
    container_name: php
    ports:
      - '80:80'
      - "443:443"
    environment:
      WEB_DOCUMENT_ROOT: "/public_html/atos"

networks:
  mongo-compose-network:
    driver: bridge