version: "2.2"
services:
  web:
    build: .
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        versao: 1
    ports:
      - "80:80"


  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: atos
      MONGO_INITDB_ROOT_PASSWORD: k2l9g3v1
    ports:
      - "27017:27017"



#  web2:
#    image: httpd:latest
#    container_name: httpd
#    restart: always
#    ports:
#      - "80:80"
#    volumes:
#      - .:/usr/local/apache2/htdocs
#    environment:
#          WORKDIR: "."
#    env_file:
#      - httpd.env
#      -


  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: k2l9g3v1
      PGDATA: /data/postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  mongo-compose-network:
    driver: bridge
  postgres:
      driver: bridge
