version: "2.2"
services:
  dev:
    volumes:
      - .:/var/www/html
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

    build: .
    expose:
      - "80"

    ports:
      - "80:80"
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: atos
      MONGO_INITDB_ROOT_PASSWORD: k2l9g3v1
    ports:
      - "27017:27017"
#  web2:
#    image: httpd:latest
#    container_name: httpd
#    restart: always
#    ports:
#      - "80:80"
#    volumes:
#      - .:/usr/local/apache2/htdocs
#    environment:
#          WORKDIR: "."
#    env_file:
#      - httpd.env
#      -


  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-k2l9g3v1}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  mongo-compose-network:
    driver: bridge